spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:26259/auth_db?user=root&password=}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: YmZha2Vfc2VjcmV0X2tleV9zaWduaW5nX2tleV93aXRoX3NhbHRfYXQtc2VjdXJpdHk=
  expirationMs: 3600000 # 1hora en ms

logging.level.org.springframework.security: DEBUG
